### ISSUE TITLE
Not compatible with the standard?

### ISSUE THREAD

**Issue by DennyWeinberg** [jan-klos/dmn_python#2]
Hi,

is it possible that your code isn't compatible with the xml schema, used by camunda and demo.bpmn.io/dmn?

Example file I used:
https://camunda.org/dmn/simulator/

**Comment by jan-klos** [comment]
If I remember corectly, Camuda and Signavio use their own xml schema. My code works on one from the official documentation (2016).

**Comment by DennyWeinberg** [comment]
ok, are you planning to extend your library?

If not, I will probabily write my own lib.

Not yet sure if it will be based on yours. Do you handle also script expressions like 'not("a","b")' and so on?

**Comment by jan-klos** [comment]
> ok, are you planning to extend your library?

No, it was only a university project.

> Do you handle also script expressions like 'not("a","b")' and so on?

No, ultimately this project only handles basic things: XML import/export, visualisation and gives some data structures.

> I will probabily write my own lib.

To be honest I think it's the best way. Thanks for your interest and let me know once you're done.

**Comment by DennyWeinberg** [comment]
ok, many thanks for your comments.

**Comment by DennyWeinberg** [comment]
I have a nice peace of code that executes my DMN Decision Table. I will work on DPMN integration and will probabily publish the code when done :)

**Comment by DennyWeinberg** [comment]
https://github.com/labsolutionlu/bpmn_dmn

**Comment by jan-klos** [comment]
Thanks for posting it. Looks like a neat work.
